# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
apt_packages:
    - libv8-dev

script:
  - R -e "devtools::install('tests/')"
  - R -f tests/test.R
